version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: deploy_scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy_scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_scripts/start_server.sh
      timeout: 300
      runas: root