version: 0.2

phases:
  install:
    commands:
      - echo Installing jQuery
      - npm install i -g jquery
      - echo Installing Bootstrap-Vue
      - npm install i -g bootstrap-vue
    build:
      Commands:
        - echo Building...
        - npm run build
        - echo Build success!
artifacts:
  files:
    - 'dist/*'