version: 0.2

phases:
  install:
    commands:
      - echo Installing jQuery
      - npm install --save jquery
      - echo Installing Bootstrap-Vue
      - npm install --save bootstrap-vue
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'