version: 0.2

phases:
  install:
    commands:
      - echo Installing (1/2) jQuery
      - npm install -g jquery
      - echo Installing (2/2) Bootstrap-Vue
      - npm install -g bootstrap-vue
    build:
      Commands:
        - echo Building...
        - npm run build
        - echo Build success!
artifacts:
  files:
    - dist/**/*